"""Add status, is_public, deleted_at, title, width, height, s3_key to videos

Revision ID: 4633f0d4a010
Revises: e3d1899f3861
Create Date: 2025-10-29 09:22:06.115988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4633f0d4a010'
down_revision: Union[str, Sequence[str], None] = 'e3d1899f3861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('status', sa.String(length=20), nullable=False, server_default='completed'))
    op.add_column('videos', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('videos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('videos', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('videos', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('s3_key', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_videos_deleted_at'), 'videos', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_videos_is_public'), 'videos', ['is_public'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_is_public'), table_name='videos')
    op.drop_index(op.f('ix_videos_deleted_at'), table_name='videos')
    op.drop_column('videos', 's3_key')
    op.drop_column('videos', 'height')
    op.drop_column('videos', 'width')
    op.drop_column('videos', 'title')
    op.drop_column('videos', 'deleted_at')
    op.drop_column('videos', 'is_public')
    op.drop_column('videos', 'status')
    # ### end Alembic commands ###
