"""Add video_glitches table

Revision ID: 8bcd681996ad
Revises: 1cfade6a98da
Create Date: 2025-10-29 07:01:33.685014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcd681996ad'
down_revision: Union[str, Sequence[str], None] = '1cfade6a98da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_glitches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_video_id', sa.UUID(), nullable=False),
    sa.Column('glitch_video_id', sa.UUID(), nullable=False),
    sa.Column('glitch_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['glitch_video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('glitch_video_id', name='unique_glitch_video')
    )
    op.create_index(op.f('ix_video_glitches_glitch_video_id'), 'video_glitches', ['glitch_video_id'], unique=False)
    op.create_index(op.f('ix_video_glitches_original_video_id'), 'video_glitches', ['original_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_glitches_original_video_id'), table_name='video_glitches')
    op.drop_index(op.f('ix_video_glitches_glitch_video_id'), table_name='video_glitches')
    op.drop_table('video_glitches')
    # ### end Alembic commands ###
