"""add_last_daily_credit_claim_to_users

Revision ID: 4b08818d25fe
Revises: 45e98842ee4a
Create Date: 2025-10-30 01:41:16.198920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b08818d25fe'
down_revision: Union[str, Sequence[str], None] = '45e98842ee4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_daily_credit_claim', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_daily_credit_claim')
    # ### end Alembic commands ###
